---
- hosts: interscity-data
  vars_files:
    - secret

  tasks:
    - name: Install ruby
      apt: pkg=ruby state=installed update_cache=true
      register: rubyinstalled

    - name: Install bundler
      apt: pkg=bundler state=installed update_cache=true
      register: bundlerinstalled
      when: rubyinstalled|success

    - name: Install bundler
      apt: pkg=nodejs state=installed update_cache=true

    - name: Install mongodb
      apt: pkg=mongodb state=installed update_cache=true
      register: mongodbinstalled
      notify:
        - Start mongodb

    - name: Clone git repo
      git: repo=https://github.com/lucaskanashiro/collect_sp_data.git dest=/opt/ accept_hostkey=true
      register: clonerepo

    - name: Install build dependencies
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - libxml2
        - zlib1g-dev
        - libpq-dev
      register: builddepsinstalled

    - name: Install script dependencies
      command: chdir=/opt bundle install --path vendor/
      when: builddepsinstalled|success
      register: scriptdepsinstalled

    - name: Create folder
      command: export INTERSCITY_DATA_FOLDER=`mktemp -d collection_data.XXX`

    - name: Load olho_vivo token
      command: export OLHO_VIVO_TOKEN=`cat /tmp/.olho_vivo_token

    - name: Add collection of weather data in crontab
      cron: name="collect weather data" minute="*/10" job="BUNDLE_GEMFILE=/opt/Gemfile bundle exec ruby /opt/weather.rb /opt/ >> /tmp/$INTERSCITY_DATA_FOLDER/weather.log 2>&1"
      when: scriptdepsinstalled|success
      notify:
        - Start cron

    - name: Add collection of air quality data in crontab
      cron: name="collect air quality data" minute="*/10" job="BUNDLE_GEMFILE=/opt/Gemfile bundle exec ruby /opt/air_quality.rb /opt/ >> /tmp/$INTERSCITY_DATA_FOLDER/air_quality.log 2>&1"
      when: scriptdepsinstalled|success
      notify:
        - Start cron

    - name: Add collection of bike stations data in crontab
      cron: name="collect bike station data" minute="*/10" job="BUNDLE_GEMFILE=/opt/Gemfile bundle exec ruby /opt/citybik.rb /opt/ >> /tmp/$INTERSCITY_DATA_FOLDER/bike_station.log 2>&1"
      when: scriptdepsinstalled|success
      notify:
        - Start cron

    - name: Add api_olhovivo data in crontab
      cron: name="olho_vivo data" minute="*/10" job="BUNDLE_GEMFILE=/opt/Gemfile bundle exec ruby /opt/olho_vivo.rb /opt/ >> /tmp/$INTERSCITY_DATA_FOLDER/olho_vivo.log 2>&1"
      when: scriptdepsinstalled|success
      notify:
        - Start cron

    - name: Install app dependencies
      command: chdir=/opt/app bundle install --path vendor/
      when: builddepsinstalled|success
      register: appinstalled

    - name: Install nginx
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - Start nginx

    - name: Create unicorn service
      command: cp /opt/playbook/unicorn_app /etc/init.d/unicorn_app
      when: clonerepo
      register: unicornservice

    - name: Make unicorn service as default
      command: update-rc.d unicorn_app defaults
      when: unicornservice
      notify:
        - Start unicorn

    - name: Copy nginx conf file
      command: cp /opt/playbook/nginx.conf /etc/nginx/sites-available/default
      when: clonerepo
      notify:
        - Start nginx

  handlers:
    - name: Start mongodb
      service: name=mongodb state=started

    - name: Start cron
      service: name=cron state=started

    - name: Start nginx
      service: name=nginx state=started

    - name: Start unicorn
      service: name=unicorn_app state=started
